server:
    servlet: 
        context-path: /api/

spring:
    application:
        name: bank_card_management_system

    datasource:
        url: jdbc:postgresql://localhost:5432/bankCardManagementSystemDb
        username: postgres
        password: postgres

    jpa:
        hibernate:
            ddl-auto: none

    liquibase:
        change-log: classpath:/db/changelog/changelog.xml
        enabled: true
