server:
    servlet: 
        context-path: /api/

spring:
    application:
        name: bank_card_management_system

    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: none

    liquibase:
        change-log: classpath:/db/changelog/changelog.xml
        enabled: true

jasypt:
    encryptor:
        password: ${JASYPT_ENCRYPTOR_PASSWORD}
        algorithm: PBEWithMD5AndDES
        iv-generator-classname: org.jasypt.iv.NoIvGenerator
        salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
        string-output-type: base64
